apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-kandidatvarsel-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{{image}}}
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{adGroupRekbisArbeidsgiverrettet}}
          - id: {{adGroupRekbisJobbsokerrettet}}
          - id: {{adGroupRekbisUtvikler}}
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
        - application: rekrutteringsbistand-sms
          namespace: toi
          cluster: {{{fssCluster}}}
    outbound:
      rules:
        - application: rekrutteringsbistand-stilling-api
  env:
    - name: AD_GROUP_REKBIS_ARBEIDSGIVERRETTET
      value: {{adGroupRekbisArbeidsgiverrettet}}
    - name: AD_GROUP_REKBIS_JOBBSOKERRETTET
      value: {{adGroupRekbisJobbsokerrettet}}
    - name: AD_GROUP_REKBIS_UTVIKLER
      value: {{adGroupRekbisUtvikler}}
    - name: AUTHORIZED_PARTY_NAMES
      value: {{adAuthorizedPartyNames}}
    - name: KANDIDATSOK_API_URL
      value: http://rekrutteringsbistand-kandidatsok-api
    {{#each env }}
    - name: {{ @key }}
      value: {{ this }}
    {{/each}}
  kafka:
    pool: {{{ kafkaPool }}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{dbTier}}
        databases:
          - name: kandidatvarsler
            envVarPrefix: DB
