apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringsbistand-kandidatvarsel-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{{image}}}
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{adGroupModiaGenerellTilgang}}
          - id: {{adGroupModiaOppfolging}}
          - id: {{adGroupRekbisArbeidsgiverrettet}}
          - id: {{adGroupRekbisJobbsokerrettet}}
          - id: {{adGroupRekbisUtvikler}}
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
  env:
    - name: AD_GROUP_MODIA_GENERELL
      value: {{adGroupModiaGenerellTilgang}}
    - name: AD_GROUP_MODIA_OPPFOLGING
      value: {{adGroupModiaOppfolging}}
    - name: AD_GROUP_REKBIS_ARBEIDSGIVERRETTET
      value: {{adGroupRekbisArbeidsgiverrettet}}
    - name: AD_GROUP_REKBIS_JOBBSOKERRETTET
      value: {{adGroupRekbisJobbsokerrettet}}
    - name: AD_GROUP_REKBIS_UTVIKLER
      value: {{adGroupRekbisUtvikler}}
    - name: AUTHORIZED_PARTY_NAMES
      value: {{adAuthorizedPartyNames}}
    {{#each env }}
    - name: {{ @key }}
      value: {{ this }}
    {{/each}}
  kafka:
    pool: {{{ kafkaPool }}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{dbTier}}
        databases:
          - name: kandidatvarsler
            envVarPrefix: DB
